d /etc/deltamud 0750 root deltamud -
d /etc/deltamud/activation 0700 root root -
d /var/lib/deltamud 0750 deltamud deltamud -
d /var/lib/deltamud/lib 0750 deltamud deltamud -
d /opt/deltamud 0755 root root -
d /opt/deltamud/releases 0755 root root -
